In [46]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [47]:
data =pd.read_csv(r"/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv")
data.head(3)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [49]:
#to check duplicated rows 
data.duplicated().sum()

0

In [50]:
#to check number of people who exited the bank and not exited 
data['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [51]:
data.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [52]:
data

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [53]:
# onhot=OneHotEncoder()
# onhot.fit_transform(data,columns=['Geography','Gender'],drop_first=True)
#df=pd.get_dummies(data,columns=['Geography','Gender'],drop_first=True)


# from sklearn.preprocessing import OneHotEncoder
# from sklearn.compose import ColumnTransformer

# # Example: Assume 'data' is a DataFrame
# categorical_features = ['Geography', 'Gender']

# column_transformer = ColumnTransformer(
#     transformers=[
#         ('encoder', OneHotEncoder(drop='first'), categorical_features)
#     ],
#     remainder='passthrough'  # keeps the other columns
# )

# transformed_data = column_transformer.fit_transform(data)



# Create dummy variables
data = pd.get_dummies(data, columns=['Geography', 'Gender'], drop_first=True)

# Convert boolean columns to integers (0 and 1)



In [54]:
data=data.astype(int)

In [55]:
data

CreditScore  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0             619   42       2        0              1          1   
1             608   41       1    83807              1          0   
2             502   42       8   159660              3          1   
3             699   39       1        0              2          0   
4             850   43       2   125510              1          1   
...           ...  ...     ...      ...            ...        ...   
9995          771   39       5        0              2          1   
9996          516   35      10    57369              1          1   
9997          709   36       7        0              1          0   
9998          772   42       3    75075              2          1   
9999          792   28       4   130142              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0                  1           101348       1                  0   
1                  1           112542       0                  0   
2                  0           113931       1                  0   
3                  0            93826       0                  0   
4                  1            79084       0                  0   
...              ...              ...     ...                ...   
9995               0            96270       0                  0   
9996               1           101699       0                  0   
9997               1            42085       1                  0   
9998               0            92888       1                  1   
9999               0            38190       0                  0   

      Geography_Spain  Gender_Male  
0                   0            0  
1                   1            0  
2                   0            0  
3                   0            0  
4                   1            0  
...               ...          ...  
9995                0            1  
9996                0            1  
9997                0            0  
9998                0            1  
9999                0            0  

[10000 rows x 12 columns]

In [56]:
x=data.drop(columns=['Exited'])
y=data['Exited']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [57]:
x_train.shape

(8000, 11)

In [58]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

# y_train_scaled=scaler.fit_transform(y_train)
# y_test_scaled=scaler.transform(y_test)
# never try to scale the target data as here y is target data , 
# if you scale it affects the result as well

In [59]:
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)


In [82]:

import tensorflow
from tensorflow import keras 
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.regularizers import l2

In [61]:
model=Sequential()

model.add(Dense(3,activation='sigmoid',input_dim=11))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [62]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_11 (Dense)                     │ (None, 3)                   │              36 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_12 (Dense)                     │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

Modal compilation 

In [63]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [64]:
model.fit(x_train_scaled,y_train,epochs=10)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7962 - loss: 0.5580
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8018 - loss: 0.4933
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7930 - loss: 0.4747
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4629
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4508
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7896 - loss: 0.4474
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8024 - loss: 0.4283
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8039 - loss: 0.4204
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8075 - loss: 0.4250
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8101 - loss: 0.4237


In [65]:
model.layers[0].get_weights()

[array([[-0.01001493,  0.12427045,  0.12854639],
        [-0.7565353 , -2.0189404 ,  0.79139686],
        [-0.05318592, -0.01418879, -0.5806021 ],
        [-0.15249328, -0.35844597,  0.73647904],
        [ 0.0882709 , -0.01038882, -0.01300235],
        [-0.07104424,  0.13075313,  0.21593818],
        [ 1.3310107 ,  0.21877606, -0.9446874 ],
        [-0.31598634,  0.14819898,  0.26375794],
        [-0.87978053, -0.14749812,  0.9694632 ],
        [-0.06898658,  0.19791943,  0.4904986 ],
        [ 0.71650195,  0.3336991 ,  0.09220644]], dtype=float32),
 array([ 0.4495926 ,  0.2909063 , -0.10582569], dtype=float32)]

In [66]:
log_pred=model.predict(x_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step  


In [67]:
log_pred

array([[0.13428968],
       [0.13614011],
       [0.1412772 ],
       ...,
       [0.05706124],
       [0.14004906],
       [0.36632472]], dtype=float32)

In [68]:
y_pred=np.where(log_pred>0.5,1,0)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [69]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.813

changes to enhance model

In [96]:
model=Sequential()

model.add(Dense(10,activation='relu',input_dim=11,kernel_regularizer=l2(0.001)))
         
model.add(Dense(16,activation='relu'))

model.add(Dense(10,activation='relu',kernel_regularizer=l2(0.001)))
model.add(Dropout(0.5))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer=keras.optimizers.Adam(learning_rate=0.0008),metrics=['accuracy'])

history=model.fit(x_train_scaled,y_train,epochs=20,validation_split=0.2)

Epoch 1/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7070 - loss: 0.6556 - val_accuracy: 0.7975 - val_loss: 0.5220
Epoch 2/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7919 - loss: 0.5316 - val_accuracy: 0.7981 - val_loss: 0.4789
Epoch 3/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7969 - loss: 0.4971 - val_accuracy: 0.8019 - val_loss: 0.4575
Epoch 4/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8082 - loss: 0.4731 - val_accuracy: 0.8056 - val_loss: 0.4481
Epoch 5/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8015 - loss: 0.4676 - val_accuracy: 0.8081 - val_loss: 0.4413
Epoch 6/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8147 - loss: 0.4366 - val_accuracy: 0.8087 - val_loss: 0.4337
Epoch 7/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8163 - loss: 0.4405 - val_accuracy: 0.8150 - val_loss: 0.4235
Epoch 8/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8148 - loss: 0.4298 - val_accuracy: 0.

In [72]:
model.layers[0].get_weights()

[array([[-0.01133298, -0.26627767, -0.11404657, -0.31834695, -0.12371539,
          0.1573265 , -0.3531115 ,  0.06019513,  0.36366588,  0.00346584,
          0.00669124,  0.03889501,  0.11036986, -0.07778285,  0.0406426 ,
          0.25796857,  0.18566033, -0.23772469,  0.07601466, -0.23352519,
          0.0239187 , -0.15907604,  0.27190667,  0.13673839, -0.10466377,
         -0.06746543, -0.1216508 ,  0.03696658,  0.02725539,  0.07640968,
         -0.31634203, -0.17800279, -0.03478681, -0.0345595 , -0.09047683,
          0.04355152, -0.37580052, -0.20046115,  0.00586089,  0.02750958,
          0.02885908, -0.24711739,  0.09447681, -0.13893867,  0.33199906,
         -0.11980575, -0.05732579,  0.1710626 ,  0.153915  , -0.02322699,
          0.37450513, -0.47110328, -0.04985603,  0.08198638, -0.1325712 ,
         -0.21939377,  0.21367931, -0.00980991, -0.09751271,  0.13659878,
          0.15975337,  0.0422479 ,  0.16161238, -0.09524637],
        [-0.27158183, -0.17162742,  0.11517815, -0

In [73]:
log_pred=model.predict(x_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [74]:
y_pred=np.where(log_pred>0.5,1,0)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [75]:
accuracy_score(y_test,y_pred)

0.854

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
history.history

In [ ]:
plt.plot(history.history['loss'])

In [ ]:

plt.plot(history.history['val_loss'])

In [ ]:
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

In [ ]:
accuracy_score(y_test,y_pred)